name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for opening an issue in my repository! I appreciate your feedback and contributions. Please provide as much detail as possible about the issue you're experiencing. If you're reporting a bug, please include steps to reproduce the issue and any error messages you're seeing. Thanks for helping me!"
        pr-message: "Thanks for opening a pull request in my repository! I appreciate your feedback and contributions. Please provide as much detail as possible about the changes you're proposing. If you're submitting a pull request, please make sure your changes are well-documented and tested. Thanks for helping me!"
